### ISSUE TITLE
CSS / JS files linked to local user

### ISSUE THREAD

**Issue by justinormont** [MaraniMatias/mdmath2html#1]
The CSS / JS files are linked to within the local user's folder. This causes the .HTML files to not render correctly on another computer. 

Example:
```html
<head>
  ...
  <link rel="stylesheet" href="C:\Users\jormont\AppData\Roaming\npm\node_modules\mdmath2html\node_modules\github-markdown-css\github-markdown.css">
  <link rel="stylesheet" href="C:\Users\jormont\AppData\Roaming\npm\node_modules\mdmath2html\node_modules\highlight.js\styles\tomorrow.css">
  ...
  <script type="text/javascript" async="" src="C:\Users\jormont\AppData\Roaming\npm\node_modules\mdmath2html\node_modules\mathjax\MathJax.js"></script>
  <script type="text/javascript" async="" src="C:\Users\jormont\AppData\Roaming\npm\node_modules\mdmath2html\node_modules\mathjax\config\TeX-MML-AM_HTMLorMML-full.js">
  ...
</head>
```

In the above, the CSS / JS files are retrieved from `C:\Users\jormont\AppData\Roaming\npm\node_modules\mdmath2html\`.

The CSS / JS files should either be linked to a CDN, embedded in the HTML file, or placed aside of the HTML file.

**Comment by MaraniMatias** [comment]
It's a very good idea, I did it so it does not depend on the internet and I try it on Linux.
